version: '3.7'

services: 
    web:
        build: .
        command: bash -c "
            python soundcloud/manage.py makemigrations &&
            python soundcloud/manage.py migrate &&
            python soundcloud/manage.py runserver 0.0.0.0:8000" &&
            npm install &&
            npm run dev
        volumes: 
            - .:/code
        ports:
            - "8000:8000" 
        depends_on: 
            - db
        links:
            - db:db
    db:
        image: postgres
        environment:
            POSTGRES_HOST_AUTH_METHOD: trust
    