# Generated by Django 3.2.5 on 2021-07-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_created=True)),
                ('username', models.CharField(max_length=120)),
                ('timestamp', models.CharField(max_length=5)),
                ('content', models.TextField()),
            ],
        ),
    ]
